/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ControllerFornecedor;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelFornecedor;
import util.BLDatas;
import util.Formatador;

/**
 *
 * @author Cliente
 */
public class viewFornecedor extends javax.swing.JFrame {

    ArrayList<ModelFornecedor> listaModelFornecedor = new ArrayList<>();

    ControllerFornecedor controlerFornecedor = new ControllerFornecedor();

    ModelFornecedor modelFornecedor = new ModelFornecedor();
    String salvarAlterar;
    Formatador formatador = new Formatador();

    BLDatas bLDatas = new BLDatas();

    /**
     * Creates new form viewFornecedor
     */
    public viewFornecedor() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        habilitarDesabilitar(false);
        carregarFornecedor();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cadastro_tipoDepessoa = new javax.swing.JPanel();
        pessoa1 = new javax.swing.JRadioButton();
        pessoa2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        for_codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        for_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        for_endereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        for_bairro = new javax.swing.JTextField();
        for_uf = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        for_cep = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        for_telefone = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        for_tabela = new javax.swing.JTable();
        for_salvar = new javax.swing.JButton();
        for_alterar = new javax.swing.JButton();
        for_novo = new javax.swing.JButton();
        for_excluir = new javax.swing.JButton();
        for_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastro_tipoDepessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo De Pessoa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        buttonGroup1.add(pessoa1);
        pessoa1.setText("Pessoa Física");

        buttonGroup1.add(pessoa2);
        pessoa2.setText("Pessoa Jurídica");

        javax.swing.GroupLayout cadastro_tipoDepessoaLayout = new javax.swing.GroupLayout(cadastro_tipoDepessoa);
        cadastro_tipoDepessoa.setLayout(cadastro_tipoDepessoaLayout);
        cadastro_tipoDepessoaLayout.setHorizontalGroup(
            cadastro_tipoDepessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastro_tipoDepessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pessoa1)
                .addGap(51, 51, 51)
                .addComponent(pessoa2)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        cadastro_tipoDepessoaLayout.setVerticalGroup(
            cadastro_tipoDepessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastro_tipoDepessoaLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(cadastro_tipoDepessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pessoa1)
                    .addComponent(pessoa2))
                .addContainerGap())
        );

        jLabel2.setText("Código");

        for_codigo.setEnabled(false);

        jLabel3.setText("Nome");

        jLabel4.setText("Endereço");

        for_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_enderecoActionPerformed(evt);
            }
        });

        jLabel5.setText("Bairro");

        for_uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel6.setText("UF:");

        try {
            for_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("CEP:");

        jLabel9.setText("Telefone:");

        try {
            for_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        for_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Endereço", "Bairro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(for_tabela);
        if (for_tabela.getColumnModel().getColumnCount() > 0) {
            for_tabela.getColumnModel().getColumn(0).setMinWidth(50);
            for_tabela.getColumnModel().getColumn(0).setPreferredWidth(50);
            for_tabela.getColumnModel().getColumn(0).setMaxWidth(50);
            for_tabela.getColumnModel().getColumn(1).setMinWidth(250);
            for_tabela.getColumnModel().getColumn(1).setPreferredWidth(250);
            for_tabela.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        for_salvar.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\save.png")); // NOI18N
        for_salvar.setText("Salvar");
        for_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_salvarActionPerformed(evt);
            }
        });

        for_alterar.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\update member.png")); // NOI18N
        for_alterar.setText("Alterar");
        for_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_alterarActionPerformed(evt);
            }
        });

        for_novo.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\add product.png")); // NOI18N
        for_novo.setText("Novo");
        for_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_novoActionPerformed(evt);
            }
        });

        for_excluir.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\delete.png")); // NOI18N
        for_excluir.setText("excluir");
        for_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_excluirActionPerformed(evt);
            }
        });

        for_cancelar.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\cancel.png")); // NOI18N
        for_cancelar.setText("Cancelar");
        for_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                for_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(for_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(for_bairro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(for_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(for_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(for_novo)
                        .addGap(101, 101, 101)
                        .addComponent(for_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(for_salvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(for_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(for_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(for_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(for_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(for_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cadastro_tipoDepessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastro_tipoDepessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(for_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(for_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(for_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(for_alterar)
                    .addComponent(for_novo)
                    .addComponent(for_excluir)
                    .addComponent(for_cancelar)
                    .addComponent(for_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void for_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_for_enderecoActionPerformed

    private void for_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_salvarActionPerformed
        // TODO add your handling code here:
        if (salvarAlterar.equals("salvar")) {
            try {
                salvarFornecedor();
            } catch (Exception ex) {
                Logger.getLogger(viewFornecedor.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (salvarAlterar.equals("alterar")) {
            alterarForncedor();
        }
    }//GEN-LAST:event_for_salvarActionPerformed

    private void for_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_alterarActionPerformed
        // TODO add your handling code here:
        salvarAlterar = "alterar";
        habilitarDesabilitar(true);
        // TODO add your handling code here:
        int linha = this.for_tabela.getSelectedRow();

        try {
            int codigo = (int) for_tabela.getValueAt(linha, 0);
            modelFornecedor = controlerFornecedor.getFornecedorController(codigo);

            for_codigo.setText(String.valueOf(modelFornecedor.getIdForncedor()));
            for_nome.setText(String.valueOf(modelFornecedor.getNomeFornecedor()));
            for_endereco.setText(modelFornecedor.getEnderecoFornecedor());
            for_bairro.setText(String.valueOf(modelFornecedor.getBairroFornecedor()));
            for_uf.setSelectedItem(String.valueOf(modelFornecedor.getUfFornecedor()));
            for_cep.setText(modelFornecedor.getCepFornecedor());
            for_telefone.setText(String.valueOf(modelFornecedor.getTelefoneFornecedor()));

            if (modelFornecedor.getPessoaFornecedor() == 1) {
                pessoa2.setSelected(true);
            }
            if (modelFornecedor.getPessoaFornecedor() == 0) {
                pessoa1.setSelected(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nem um registro selecionado!", "Aviso", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_for_alterarActionPerformed

    private void for_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_novoActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitar(true);
        salvarAlterar = "salvar";
    }//GEN-LAST:event_for_novoActionPerformed

    private void for_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_excluirActionPerformed
        // TODO add your handling code here:
        modelFornecedor = new ModelFornecedor();
        int linha = for_tabela.getSelectedRow();

        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione algum nome na tabela", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {

            int certeza = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o fornecedor?");
            if (certeza == JOptionPane.OK_OPTION) {
                int codigo = (int) for_tabela.getValueAt(linha, 0);
                if (controlerFornecedor.excluirFornecedorController(codigo)) {
                }
            }
            this.carregarFornecedor();
        }
    }//GEN-LAST:event_for_excluirActionPerformed

    private void for_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_for_cancelarActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitar(false);
        this.limparTela();
    }//GEN-LAST:event_for_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cadastro_tipoDepessoa;
    private javax.swing.JButton for_alterar;
    private javax.swing.JTextField for_bairro;
    private javax.swing.JButton for_cancelar;
    private javax.swing.JFormattedTextField for_cep;
    private javax.swing.JTextField for_codigo;
    private javax.swing.JTextField for_endereco;
    private javax.swing.JButton for_excluir;
    private javax.swing.JTextField for_nome;
    private javax.swing.JButton for_novo;
    private javax.swing.JButton for_salvar;
    private javax.swing.JTable for_tabela;
    private javax.swing.JFormattedTextField for_telefone;
    private javax.swing.JComboBox for_uf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton pessoa1;
    private javax.swing.JRadioButton pessoa2;
    // End of variables declaration//GEN-END:variables

    private void salvarFornecedor() throws Exception {

        modelFornecedor.setNomeFornecedor(this.for_nome.getText().toUpperCase());
        modelFornecedor.setEnderecoFornecedor(this.for_endereco.getText().toUpperCase());
        modelFornecedor.setBairroFornecedor(this.for_bairro.getText().toUpperCase());
        modelFornecedor.setUfFornecedor(this.for_uf.getSelectedItem().toString());
        modelFornecedor.setCepFornecedor(this.for_cep.getText());
        modelFornecedor.setTelefoneFornecedor(this.for_telefone.getText());
        modelFornecedor.setData(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));

        if (pessoa1.isSelected()) {
            modelFornecedor.setPessoaFornecedor(0);
        }

        if (pessoa2.isSelected()) {
            modelFornecedor.setPessoaFornecedor(1);
        }

        if (controlerFornecedor.salvarFornecedorController(modelFornecedor) > 0) {
            JOptionPane.showMessageDialog(this, "Fornecedor salvo com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            this.carregarFornecedor();
            this.limparTela();
            this.habilitarDesabilitar(false);

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o fornecedor!", "Erro", JOptionPane.ERROR_MESSAGE);

        }

    }

    private void alterarForncedor() {
        modelFornecedor.setNomeFornecedor(this.for_nome.getText().toUpperCase());
        modelFornecedor.setEnderecoFornecedor(this.for_endereco.getText().toUpperCase());
        modelFornecedor.setBairroFornecedor(this.for_bairro.getText().toUpperCase());
        modelFornecedor.setUfFornecedor(this.for_uf.getSelectedItem().toString());
        modelFornecedor.setCepFornecedor(this.for_cep.getText());
        modelFornecedor.setTelefoneFornecedor(this.for_telefone.getText());

        if (pessoa1.isSelected()) {
            modelFornecedor.setPessoaFornecedor(0);
        } else if (pessoa2.isSelected()) {
            modelFornecedor.setPessoaFornecedor(1);

        }

        if (controlerFornecedor.atualizarFornecedorController(modelFornecedor)) {
            JOptionPane.showMessageDialog(this, "Fornecedor alterador com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            this.carregarFornecedor();
            this.limparTela();
            this.habilitarDesabilitar(false);

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar o fornecedor!", "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }

    void limparTela() {
        for_nome.setText("");
        for_endereco.setText("");
        for_bairro.setText("");
        for_cep.setText("");
        for_telefone.setText("");
        pessoa1.setSelected(false);
        pessoa2.setSelected(false);
    }

    private void habilitarDesabilitar(boolean codicao) {
        for_nome.setEnabled(codicao);
        for_endereco.setEnabled(codicao);
        for_bairro.setEnabled(codicao);
        for_cep.setEnabled(codicao);
        for_telefone.setEnabled(codicao);
        pessoa1.setEnabled(codicao);
        pessoa2.setEnabled(codicao);
        for_uf.setEnabled(codicao);
    }

    void carregarFornecedor() {
        listaModelFornecedor = controlerFornecedor.getListaFornecedorController();

        DefaultTableModel modelo = (DefaultTableModel) for_tabela.getModel();

        modelo.setRowCount(0);
        // inserir prodtus na tabela
        for (int i = 0; i < listaModelFornecedor.size(); i++) {
            modelo.addRow(new Object[]{
                listaModelFornecedor.get(i).getIdForncedor(),
                listaModelFornecedor.get(i).getNomeFornecedor(),
                listaModelFornecedor.get(i).getEnderecoFornecedor(),
                listaModelFornecedor.get(i).getBairroFornecedor()
            });
        }
    }

}
