/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.ControllerDetalhes;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.ModelDetalhes;

/**
 *
 * @author Cliente
 */
public class viewDetalhes extends javax.swing.JFrame {

    ControllerDetalhes controllerDetalhes = new ControllerDetalhes();
    ModelDetalhes modelDetalhes = new ModelDetalhes();
    String caminho = "semImagem";
    BufferedImage imagemBuffer = null;
    ByteArrayOutputStream bytesImg = new ByteArrayOutputStream();
    String SalvarAlterar = "salvar";

    /**
     * Creates new form viewDetalhes
     */
    public viewDetalhes() throws IOException {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        del_codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        del_nome = new javax.swing.JTextField();
        de_idde = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        del_cor = new javax.swing.JTextField();
        del_marca = new javax.swing.JTextField();
        del_tamanho = new javax.swing.JFormattedTextField();
        del_alterar = new javax.swing.JButton();
        del_salvar = new javax.swing.JButton();
        cad_InserirFoto = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton3.setText("salvar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setText("Código");

        del_codigo.setEnabled(false);

        jLabel3.setText("Nome");

        del_nome.setEnabled(false);

        de_idde.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(del_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(del_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(de_idde, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(del_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(de_idde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(del_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setText("Tamanho");

        jLabel5.setText("Cor");

        jLabel6.setText("Marca");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(del_tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(del_marca)
                    .addComponent(del_cor)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(del_tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(del_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(del_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        del_alterar.setText("Alterar");
        del_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_alterarActionPerformed(evt);
            }
        });

        del_salvar.setText("Salvar");
        del_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_salvarActionPerformed(evt);
            }
        });

        cad_InserirFoto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cad_InserirFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cad_InserirFoto.setText("Inserir imagem");
        cad_InserirFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cad_InserirFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cad_InserirFotoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cad_InserirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(del_alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(del_salvar)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cad_InserirFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(del_salvar)
                            .addComponent(del_alterar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void del_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_salvarActionPerformed
        // TODO add your handling code here:

        if (SalvarAlterar.equals("salvar")) {

            modelDetalhes = new ModelDetalhes();
            modelDetalhes.setPkIdDetalhe(8);
            modelDetalhes.setPkIdProdutos(5);
            modelDetalhes.setpNome("ff");
            modelDetalhes.setTblCor(del_cor.getText());
            modelDetalhes.setTblTamanho(Integer.valueOf(del_tamanho.getText()));
            modelDetalhes.setTblImagem(caminho);
            modelDetalhes.setTblMarca("gggg");
            System.out.println(modelDetalhes);

            if (controllerDetalhes.salvarDetalhesController(modelDetalhes) > 0) {
                JOptionPane.showMessageDialog(this, "Salvo com sucesso", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpar();
                SalvarAlterar = "salvar";
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar", "Aviso", JOptionPane.ERROR_MESSAGE);
                SalvarAlterar = "salvar";

            }
        } else if (SalvarAlterar.equals("alterar")) {
            modelDetalhes.setpNome("ff");
            modelDetalhes.setTblCor(del_cor.getText());
            modelDetalhes.setTblTamanho(Integer.valueOf(del_tamanho.getText()));
            modelDetalhes.setTblImagem(caminho);
            modelDetalhes.setTblMarca(del_marca.getText());

            if (controllerDetalhes.atualizarDetalhesController(modelDetalhes)) {
                JOptionPane.showMessageDialog(this, "Alterado com sucesso", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpar();
                SalvarAlterar = "salvar";

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Alterar", "Aviso", JOptionPane.ERROR_MESSAGE);
                SalvarAlterar = "salvar";

            }

        }

    }//GEN-LAST:event_del_salvarActionPerformed

    private void cad_InserirFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cad_InserirFotoMouseClicked
        try {
            receberImagem();
        } catch (IOException ex) {
            Logger.getLogger(viewDetalhes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cad_InserirFotoMouseClicked

    private void del_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_alterarActionPerformed
        // TODO add your handling code here:

        SalvarAlterar = "alterar";
        modelDetalhes = new ModelDetalhes();
        String caminhoImagem;

        // código de produto
        int codigo = 8;

        modelDetalhes = controllerDetalhes.getDetalhesController(codigo);
        del_codigo.setText(String.valueOf(modelDetalhes.getPkIdProdutos()));

        del_tamanho.setText(String.valueOf(modelDetalhes.getTblTamanho()));
        del_cor.setText(modelDetalhes.getTblCor());
        del_marca.setText(modelDetalhes.getTblMarca());
        de_idde.setText(String.valueOf(modelDetalhes.getPkIdDetalhe()));
        del_nome.setText(modelDetalhes.getpNome());

        caminhoImagem = modelDetalhes.getTblImagem();
        int tamanhoDaString = caminhoImagem.length() + 2;
        char[] armazernarFoto = new char[tamanhoDaString];

        for (int i = 0, j = 0; j < caminhoImagem.length(); i++, j++) {

            // acrescentar "\" na array 1
            if (i == 2) {
                armazernarFoto[i] = 92;
                i = i + 1;

            }

            // acrescentar "\" na array 5
            if (i == 8) {
                armazernarFoto[i] = 92;
                i = i + 1;
            }

            armazernarFoto[i] = caminhoImagem.charAt(j);

        }

        // Converter a array em uma String
        String caminhoDaImagem = String.valueOf(armazernarFoto);
        System.out.println(caminhoDaImagem);
        //Retornando a foto 
        ImageIcon minhaImagem = new ImageIcon(caminhoDaImagem);

        Image img = minhaImagem.getImage();

        Image novaImage = img.getScaledInstance(cad_InserirFoto.getWidth(), cad_InserirFoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(novaImage);
        cad_InserirFoto.setIcon(image);
    }//GEN-LAST:event_del_alterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewDetalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new viewDetalhes().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(viewDetalhes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cad_InserirFoto;
    private javax.swing.JTextField de_idde;
    private javax.swing.JButton del_alterar;
    private javax.swing.JTextField del_codigo;
    private javax.swing.JTextField del_cor;
    private javax.swing.JTextField del_marca;
    private javax.swing.JTextField del_nome;
    private javax.swing.JButton del_salvar;
    private javax.swing.JFormattedTextField del_tamanho;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

    public String receberImagem() throws IOException {

        caminho = new String();

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagens em JPEG E PNG", "jpg", "png");
        fileChooser.addChoosableFileFilter(filtro);

        fileChooser.setAcceptAllFileFilterUsed(false);

        fileChooser.setDialogType(JFileChooser.OPEN_DIALOG);
        fileChooser.setCurrentDirectory(new File("C:/Fotos"));
        fileChooser.showOpenDialog(this);

        caminho = fileChooser.getSelectedFile().getAbsolutePath();
//
//      imagemBuffer = ImageIO.read(new File(caminho));
//     Image diminuirImagem = imagemBuffer.getScaledInstance(290, 100, 0);
//       imagemLabel.setIcon(new ImageIcon(diminuirImagem));
        ImageIcon minhaImagem = new ImageIcon(caminho);

        Image img = minhaImagem.getImage();

        Image novaImage = img.getScaledInstance(cad_InserirFoto.getWidth(), cad_InserirFoto.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(novaImage);
        cad_InserirFoto.setIcon(image);

        return caminho;

    }

    void limpar() {
        del_tamanho.setText("");
        del_cor.setText("");
        del_marca.setText("");
        cad_InserirFoto.setIcon(null);
    }

    public void receberInformacoes(int pIdDetalhe ) {

        modelDetalhes = new ModelDetalhes();
        modelDetalhes = controllerDetalhes.getDetalhesController(pIdDetalhe);

        del_codigo.setText(modelDetalhes.getPkIdProdutos() + "");
        del_nome.setText(modelDetalhes.getpNome());

    }

}
