/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import controler.ControllerFornecedor;
import controler.ControllerProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelProduto;
import model.ProdutosDetalhes;
import util.Formatador;
import controler.ControllerProdutosDetalhes;
import model.ModelFornecedor;

/**
 *
 * @author Cliente
 */
public class viewProduto extends javax.swing.JFrame {

    ArrayList<ModelProduto> listaModelProduto = new ArrayList<>();
    ControllerProduto controllerModelProdutos = new ControllerProduto();
    ModelProduto modelProduto = new ModelProduto();
    String salvarAlterar;
    Formatador formatador = new Formatador();

    ModelFornecedor modelfornecedor = new ModelFornecedor();
    ControllerFornecedor ControllerFornecedor = new ControllerFornecedor();
    ArrayList<ModelFornecedor> listaModelFornecedor = new ArrayList<>();

    /**
     * Creates new form viewProduto
     */
    public viewProduto() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        carregarProdutos();
        habilitarDesabilitar(false);
        preencherListarFornecedor();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        produto_codigo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        produto_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        produto_pesquisa = new javax.swing.JTextField();
        produto_pesquisaBotao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        produto_tabela = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        produto_estoque = new javax.swing.JFormattedTextField();
        produto_valor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cod_fornecedor = new javax.swing.JTextField();
        cb_fornecedor = new componentes.UJComboBox();
        produto_nome = new javax.swing.JTextField();
        det_masculino = new javax.swing.JRadioButton();
        det_feminino = new javax.swing.JRadioButton();
        det_infantil = new javax.swing.JRadioButton();
        det_outros = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        det_tamanho = new componentes.UJComboBox();
        jLabel10 = new javax.swing.JLabel();
        det_cor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        det_obs = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");

        jLabel1.setText("Código Prod:");

        produto_id.setEditable(false);
        produto_id.setEnabled(false);

        jLabel2.setText("Marca:");

        jLabel3.setText("Estoque:");

        jLabel4.setText("Valor:");

        jLabel5.setText("Pesquisa:");

        produto_pesquisaBotao.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\search1.png")); // NOI18N
        produto_pesquisaBotao.setText("Pesquisa");
        produto_pesquisaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produto_pesquisaBotaoActionPerformed(evt);
            }
        });

        produto_tabela.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        produto_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(produto_tabela);
        if (produto_tabela.getColumnModel().getColumnCount() > 0) {
            produto_tabela.getColumnModel().getColumn(1).setMinWidth(230);
            produto_tabela.getColumnModel().getColumn(1).setPreferredWidth(230);
            produto_tabela.getColumnModel().getColumn(1).setMaxWidth(230);
        }

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\cancel.png")); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\ediit.png")); // NOI18N
        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\delete1.png")); // NOI18N
        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\upload.png")); // NOI18N
        jButton5.setText("Novo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\save.png")); // NOI18N
        jButton6.setText("Salvar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        produto_estoque.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel6.setText("Código Forn:");

        jLabel7.setText("Fornecedor:");

        cod_fornecedor.setEditable(false);
        cod_fornecedor.setAutoscrolls(false);
        cod_fornecedor.setEnabled(false);
        cod_fornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cod_fornecedorFocusLost(evt);
            }
        });

        cb_fornecedor.setAutocompletar(true);
        cb_fornecedor.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cb_fornecedorPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        buttonGroup1.add(det_masculino);
        det_masculino.setText("Masculino");

        buttonGroup1.add(det_feminino);
        det_feminino.setText("Feminino");

        buttonGroup1.add(det_infantil);
        det_infantil.setText("Infantil");
        det_infantil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                det_infantilActionPerformed(evt);
            }
        });

        buttonGroup1.add(det_outros);
        det_outros.setText("Outros");

        jLabel9.setText("Tamanho");

        det_tamanho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48" }));
        det_tamanho.setAutocompletar(true);
        det_tamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                det_tamanhoActionPerformed(evt);
            }
        });

        jLabel10.setText("Cor");

        jLabel11.setText("Obs");

        jLabel12.setText("Gênero:");

        javax.swing.GroupLayout produto_codigoLayout = new javax.swing.GroupLayout(produto_codigo);
        produto_codigo.setLayout(produto_codigoLayout);
        produto_codigoLayout.setHorizontalGroup(
            produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produto_codigoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(produto_codigoLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(produto_codigoLayout.createSequentialGroup()
                        .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(produto_codigoLayout.createSequentialGroup()
                                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(produto_codigoLayout.createSequentialGroup()
                                        .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cod_fornecedor))
                                        .addGap(18, 18, 18)
                                        .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(cb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(produto_codigoLayout.createSequentialGroup()
                                        .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(produto_codigoLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(produto_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(produto_pesquisaBotao))
                                            .addGroup(produto_codigoLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel10))))
                                    .addGroup(produto_codigoLayout.createSequentialGroup()
                                        .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(det_tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(produto_id, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                            .addComponent(produto_estoque, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(produto_codigoLayout.createSequentialGroup()
                                                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(produto_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(produto_codigoLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(det_masculino)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(det_feminino)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(det_infantil)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(det_outros))
                                                    .addGroup(produto_codigoLayout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(jLabel12))))
                                            .addComponent(jLabel2)
                                            .addComponent(produto_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(produto_codigoLayout.createSequentialGroup()
                                                .addComponent(det_cor)
                                                .addGap(130, 130, 130))))
                                    .addComponent(jLabel11)
                                    .addComponent(det_obs, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        produto_codigoLayout.setVerticalGroup(
            produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produto_codigoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(produto_codigoLayout.createSequentialGroup()
                        .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(produto_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(produto_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(produto_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(produto_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(det_masculino)
                        .addComponent(det_feminino)
                        .addComponent(det_infantil)
                        .addComponent(det_outros)))
                .addGap(18, 18, 18)
                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(det_cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(det_tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(det_obs, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(produto_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(produto_pesquisaBotao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(produto_codigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(produto_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(produto_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (salvarAlterar.equals("salvar")) {
            salvarProduto();
        } else if (salvarAlterar.equals("alterar")) {
            alterarProduto();
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        modelProduto = new ModelProduto();
        int linha = produto_tabela.getSelectedRow();

        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione algum nome na tabela", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {

            int certeza = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o produto?");
            if (certeza == JOptionPane.OK_OPTION) {

                int codigo = (int) produto_tabela.getValueAt(linha, 0);
                if (controllerModelProdutos.excluirProdutoController(codigo)) {
                    JOptionPane.showMessageDialog(this, "Excluido com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(this, "O produto não pode ser excluido!", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                }

            }
            this.carregarProdutos();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitar(true);
        salvarAlterar = "salvar";
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitar(false);
        this.limparTela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        salvarAlterar = "alterar";
        habilitarDesabilitar(true);
        // TODO add your handling code here:
        int linha = this.produto_tabela.getSelectedRow();

        try {
            int codigo = (int) produto_tabela.getValueAt(linha, 0);

            modelProduto = controllerModelProdutos.getProdutoController(codigo);

            produto_id.setText(String.valueOf(codigo));
            produto_nome.setText(modelProduto.getProNome());
            produto_estoque.setText(String.valueOf(modelProduto.getProEstoque()));
            produto_valor.setText(String.valueOf(modelProduto.getProValor()));
            det_cor.setText(modelProduto.getProCor());
            det_obs.setText(modelProduto.getProObs());
            det_tamanho.setSelectedItem(modelProduto.getProTamanho());
            cod_fornecedor.setText(String.valueOf(modelProduto.getPro_idFornecedor()));
            cb_fornecedor.setSelectedItem(modelProduto.getProNome());

            modelfornecedor = ControllerFornecedor.getFornecedorController(modelProduto.getPro_idFornecedor());
            cb_fornecedor.setSelectedItem((modelfornecedor.getNomeFornecedor()));

            if (modelProduto.getProGenero().equals("MASCULINO")) {
                det_masculino.setSelected(true);
            }
            if (modelProduto.getProGenero().equals("FEMININO")) {
                det_feminino.setSelected(true);
            }
            if (modelProduto.getProGenero().equals("INFANTIL")) {
                det_infantil.setSelected(true);
            }
            if (modelProduto.getProGenero().equals("OUTROS")) {
                det_outros.setSelected(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nem um registro selecionado!", "Aviso", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void produto_pesquisaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produto_pesquisaBotaoActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.produto_tabela.getModel();
        //pesquisar na tabela.
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.produto_tabela.setRowSorter(classificador);

        // texto digitado
        String texto = produto_pesquisa.getText();

        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));

    }//GEN-LAST:event_produto_pesquisaBotaoActionPerformed

    private void det_infantilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_det_infantilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_det_infantilActionPerformed

    private void cb_fornecedorPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_fornecedorPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (cb_fornecedor.isPopupVisible()) {
         modelfornecedor = ControllerFornecedor.getFornecedorController(cb_fornecedor.getSelectedItem().toString());
            cod_fornecedor.setText(String.valueOf(modelfornecedor.getIdForncedor()));
        }
    }//GEN-LAST:event_cb_fornecedorPopupMenuWillBecomeInvisible

    private void cod_fornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cod_fornecedorFocusLost
        // TODO add your handling code here:
        try {
            modelfornecedor = ControllerFornecedor.getFornecedorController(Integer.valueOf(cod_fornecedor.getText()));
            cb_fornecedor.setSelectedItem(modelfornecedor.getNomeFornecedor());
        } catch (NumberFormatException e) {
        }
    }//GEN-LAST:event_cod_fornecedorFocusLost

    private void det_tamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_det_tamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_det_tamanhoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private componentes.UJComboBox cb_fornecedor;
    private javax.swing.JTextField cod_fornecedor;
    private javax.swing.JTextField det_cor;
    private javax.swing.JRadioButton det_feminino;
    private javax.swing.JRadioButton det_infantil;
    private javax.swing.JRadioButton det_masculino;
    private javax.swing.JTextField det_obs;
    private javax.swing.JRadioButton det_outros;
    private componentes.UJComboBox det_tamanho;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel produto_codigo;
    private javax.swing.JFormattedTextField produto_estoque;
    private javax.swing.JTextField produto_id;
    private javax.swing.JTextField produto_nome;
    private javax.swing.JTextField produto_pesquisa;
    private javax.swing.JButton produto_pesquisaBotao;
    private javax.swing.JTable produto_tabela;
    private javax.swing.JTextField produto_valor;
    // End of variables declaration//GEN-END:variables

    private void carregarProdutos() {

        ProdutosDetalhes produtosDetalhes = new ProdutosDetalhes();
        listaModelProduto = new ArrayList<>();
        listaModelProduto = controllerModelProdutos.getListaProdutoController();

        DefaultTableModel modelo = (DefaultTableModel) produto_tabela.getModel();
        modelo.setRowCount(0);
        // inserir prodtus na tabela
        for (int i = 0; i < listaModelProduto.size(); i++) {
            modelo.addRow(new Object[]{
                listaModelProduto.get(i).getIdProduto(),
                listaModelProduto.get(i).getProNome(),
                listaModelProduto.get(i).getProEstoque(),
                listaModelProduto.get(i).getProValor()

            });
        }

    }

    private void habilitarDesabilitar(boolean codicao) {
        produto_nome.setEnabled(codicao);
        produto_estoque.setEnabled(codicao);
        produto_valor.setEnabled(codicao);
        cb_fornecedor.setEnabled(codicao);
        det_tamanho.setEnabled(codicao);
        det_cor.setEnabled(codicao);
        det_obs.setEnabled(codicao);
        det_masculino.setEnabled(codicao);
        det_feminino.setEnabled(codicao);
        det_infantil.setEnabled(codicao);
        det_outros.setEnabled(codicao);
    }

    private void limparTela() {
        produto_nome.setText("");
        produto_estoque.setText("");
        produto_valor.setText("");
        cb_fornecedor.setSelectedIndex(0);
        det_tamanho.setSelectedItem("-");
        det_cor.setText("");
        det_obs.setText("");
    }

    private void salvarProduto() {

        try {
            modelProduto.setIdProduto(Integer.valueOf(this.cod_fornecedor.getText()));
            modelProduto.setProTamanho(Integer.valueOf(det_tamanho.getSelectedItem().toString()));

        } catch (NumberFormatException e) {
        }

        try {
            modelProduto.setPro_idFornecedor(Integer.valueOf(this.cod_fornecedor.getText()));
            modelProduto.setProNome(this.produto_nome.getText().toUpperCase());
            modelProduto.setProEstoque(Integer.valueOf(this.produto_estoque.getText()));
            modelProduto.setProValor(formatador.converterVirgulaParaPonto(this.produto_valor.getText()));
            modelProduto.setProMarca("x");

            if (det_masculino.isSelected()) {
                modelProduto.setProGenero("MASCULINO");
            }
            if (det_feminino.isSelected()) {
                modelProduto.setProGenero("FEMININO");
            }
            if (det_infantil.isSelected()) {
                modelProduto.setProGenero("INFANTIL");
            }
            if (det_outros.isSelected()) {
                modelProduto.setProGenero("OUTROS");
            }

            modelProduto.setProCor(det_cor.getText().toUpperCase());
            modelProduto.setProObs(det_obs.getText().toUpperCase());

            if (controllerModelProdutos.salvarProdutoController(modelProduto) > 0) {
                JOptionPane.showMessageDialog(this, "Produto salvo com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                this.carregarProdutos();
                this.limparTela();
                this.habilitarDesabilitar(false);

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar o produto!", "Erro", JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Complete todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
            modelProduto.setProTamanho(0);
        }

    }

    private void alterarProduto() {

        if (det_tamanho.getSelectedItem().equals("-")) {
            modelProduto.setProTamanho(0);
        } else {
            modelProduto.setProTamanho(Integer.valueOf(det_tamanho.getSelectedItem().toString()));
        }

        try {
            modelProduto.setPro_idFornecedor(Integer.valueOf(this.cod_fornecedor.getText()));
            modelProduto.setProNome(this.produto_nome.getText().toUpperCase());
            modelProduto.setProEstoque(Integer.valueOf(this.produto_estoque.getText()));
            modelProduto.setProValor(formatador.converterVirgulaParaPonto(this.produto_valor.getText()));
            modelProduto.setProMarca("x");

            if (det_masculino.isSelected()) {
                modelProduto.setProGenero("MASCULINO");
            }
            if (det_feminino.isSelected()) {
                modelProduto.setProGenero("FEMININO");
            }
            if (det_infantil.isSelected()) {
                modelProduto.setProGenero("INFANTIL");
            }
            if (det_outros.isSelected()) {
                modelProduto.setProGenero("OUTROS");
            }

            modelProduto.setProCor(det_cor.getText().toUpperCase());
            modelProduto.setProObs(det_obs.getText().toUpperCase());

            if (controllerModelProdutos.atualizarProdutoController(modelProduto)) {
                JOptionPane.showMessageDialog(this, "Produto Alterado com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                this.carregarProdutos();
                this.limparTela();
                this.habilitarDesabilitar(false);

            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar o produto!", "Erro", JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Complete todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
            modelProduto.setProTamanho(0);
        }
    }

    private void preencherListarFornecedor() {
        listaModelFornecedor = ControllerFornecedor.getListaFornecedorController();
        cb_fornecedor.removeAllItems();
        for (int i = 0; i < listaModelFornecedor.size(); i++) {
            cb_fornecedor.addItem(listaModelFornecedor.get(i).getNomeFornecedor());
        }
    }

}
