/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.Controllercliente;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Modelcliente;
import util.Formatador;

/**
 *
 * @author Cliente
 */
public class viewCadastro extends javax.swing.JFrame {

    ArrayList<Modelcliente> listaModelCliente = new ArrayList<>();

    Controllercliente controllerModelCliente = new Controllercliente();

    Modelcliente modelCliente = new Modelcliente();
    String salvarAlterar;
    Formatador formatador = new Formatador();

    /**
     *
     * /**
     * Creates new form viewCadastro
     */
    public viewCadastro() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
        setLocationRelativeTo(null);
        habilitarDesabilitar(false);
        carregarCliente();
        viewCadastroTabela.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        viewCadastroCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        viewCadastroNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        viewCadastroEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        viewCadastroBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        viewCadatroCidade = new javax.swing.JTextField();
        viewCadastroUF = new javax.swing.JComboBox();
        viewCadastroCEP = new javax.swing.JFormattedTextField();
        viewCadastroTelefone = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewCadastroTabela = new javax.swing.JTable();
        viewCadastroCancelar = new javax.swing.JButton();
        viewCadastroNovo = new javax.swing.JButton();
        viewCadastroAlterar = new javax.swing.JButton();
        viewCadastroSalvar = new javax.swing.JButton();
        cadastrar_excluir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cadastro_pesquisar = new javax.swing.JTextField();
        cadastro_botaopesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");

        jLabel1.setText("Código:");

        viewCadastroCodigo.setEnabled(false);

        jLabel2.setText("Nome:");

        jLabel3.setText("Endereço:");

        viewCadastroEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCadastroEnderecoActionPerformed(evt);
            }
        });

        jLabel4.setText("Bairro:");

        jLabel5.setText("Cidade:");

        jLabel6.setText("UF:");

        jLabel7.setText("CEP:");

        jLabel8.setText("Telefone:");

        viewCadastroUF.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        try {
            viewCadastroCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            viewCadastroTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        viewCadastroTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome do Cliente", "Cidade", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewCadastroTabela);
        if (viewCadastroTabela.getColumnModel().getColumnCount() > 0) {
            viewCadastroTabela.getColumnModel().getColumn(0).setMinWidth(70);
            viewCadastroTabela.getColumnModel().getColumn(0).setPreferredWidth(70);
            viewCadastroTabela.getColumnModel().getColumn(0).setMaxWidth(70);
            viewCadastroTabela.getColumnModel().getColumn(1).setMinWidth(250);
            viewCadastroTabela.getColumnModel().getColumn(1).setPreferredWidth(250);
            viewCadastroTabela.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        viewCadastroCancelar.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\cancel.png")); // NOI18N
        viewCadastroCancelar.setText("Cancelar");
        viewCadastroCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCadastroCancelarActionPerformed(evt);
            }
        });

        viewCadastroNovo.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\add product.png")); // NOI18N
        viewCadastroNovo.setText("Novo");
        viewCadastroNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCadastroNovoActionPerformed(evt);
            }
        });

        viewCadastroAlterar.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\update member.png")); // NOI18N
        viewCadastroAlterar.setText("Alterar");
        viewCadastroAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCadastroAlterarActionPerformed(evt);
            }
        });

        viewCadastroSalvar.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\save.png")); // NOI18N
        viewCadastroSalvar.setText("Salvar");
        viewCadastroSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCadastroSalvarActionPerformed(evt);
            }
        });

        cadastrar_excluir.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\delete.png")); // NOI18N
        cadastrar_excluir.setText("excluir");
        cadastrar_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrar_excluirActionPerformed(evt);
            }
        });

        jLabel9.setText("Pesquisar Cliente:");

        cadastro_botaopesquisar.setIcon(new javax.swing.ImageIcon("C:\\vendas\\src\\imagens\\search1.png")); // NOI18N
        cadastro_botaopesquisar.setText("Pesquisar");
        cadastro_botaopesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastro_botaopesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewCadastroCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrar_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewCadastroNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewCadastroAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewCadastroSalvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(viewCadastroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(viewCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viewCadatroCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(viewCadastroEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewCadastroUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(viewCadastroCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(viewCadastroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(viewCadastroBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastro_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cadastro_botaopesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCadastroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCadastroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCadastroBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewCadatroCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewCadastroUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewCadastroCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewCadastroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cadastro_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastro_botaopesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewCadastroCancelar)
                    .addComponent(viewCadastroNovo)
                    .addComponent(viewCadastroAlterar)
                    .addComponent(viewCadastroSalvar)
                    .addComponent(cadastrar_excluir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewCadastroEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCadastroEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewCadastroEnderecoActionPerformed

    private void viewCadastroSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCadastroSalvarActionPerformed
        // TODO add your handling code here:
        if (salvarAlterar.equals("salvar")) {
            salvarCliente();
        } else if (salvarAlterar.equals("alterar")) {
            alterarCliente();
        }

    }//GEN-LAST:event_viewCadastroSalvarActionPerformed

    private void viewCadastroNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCadastroNovoActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitar(true);
        salvarAlterar = "salvar";
    }//GEN-LAST:event_viewCadastroNovoActionPerformed

    private void viewCadastroCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCadastroCancelarActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitar(false);
        this.limparTela();

    }//GEN-LAST:event_viewCadastroCancelarActionPerformed

    private void viewCadastroAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCadastroAlterarActionPerformed
        // TODO add your handling code here:
        salvarAlterar = "alterar";
        habilitarDesabilitar(true);
        // TODO add your handling code here:
        int linha = this.viewCadastroTabela.getSelectedRow();

        try {
            int codigo = (int) viewCadastroTabela.getValueAt(linha, 0);
            modelCliente = controllerModelCliente.getclienteController(codigo);

            viewCadastroCodigo.setText(String.valueOf(modelCliente.getIdCliente()));
            viewCadastroNome.setText(String.valueOf(modelCliente.getCliNome()));
            viewCadastroEndereco.setText(modelCliente.getCliEndereco());
            viewCadastroBairro.setText(String.valueOf(modelCliente.getCliBairro()));
            viewCadatroCidade.setText(String.valueOf(modelCliente.getCliCidade()));
            viewCadastroUF.setSelectedItem(modelCliente.getCliUF());
            viewCadastroCEP.setText(String.valueOf(modelCliente.getClicep()));
            viewCadastroTelefone.setText(String.valueOf(modelCliente.getCliTelefone()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código inválido ou nem um registro selecionado!", "Aviso", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_viewCadastroAlterarActionPerformed

    private void cadastrar_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrar_excluirActionPerformed
        // TODO add your handling code here:
        modelCliente = new Modelcliente();
        int linha = viewCadastroTabela.getSelectedRow();

        if (linha < 0) {
            JOptionPane.showMessageDialog(this, "Selecione algum nome na tabela", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {

            int certeza = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir o cliente?");
            if (certeza == JOptionPane.OK_OPTION) {
                int codigo = (int) viewCadastroTabela.getValueAt(linha, 0);
                if (controllerModelCliente.excluirclienteController(codigo)) {
                }
            }
            this.carregarCliente();
        }
    }//GEN-LAST:event_cadastrar_excluirActionPerformed

    private void cadastro_botaopesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastro_botaopesquisarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.viewCadastroTabela.getModel();
        //pesquisar na tabela.
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.viewCadastroTabela.setRowSorter(classificador);

        // texto digitado
        String texto = cadastro_pesquisar.getText().toUpperCase();
          System.out.println(texto);
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));

            
    }//GEN-LAST:event_cadastro_botaopesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar_excluir;
    private javax.swing.JButton cadastro_botaopesquisar;
    private javax.swing.JTextField cadastro_pesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewCadastroAlterar;
    private javax.swing.JTextField viewCadastroBairro;
    private javax.swing.JFormattedTextField viewCadastroCEP;
    private javax.swing.JButton viewCadastroCancelar;
    private javax.swing.JTextField viewCadastroCodigo;
    private javax.swing.JTextField viewCadastroEndereco;
    private javax.swing.JTextField viewCadastroNome;
    private javax.swing.JButton viewCadastroNovo;
    private javax.swing.JButton viewCadastroSalvar;
    private javax.swing.JTable viewCadastroTabela;
    private javax.swing.JFormattedTextField viewCadastroTelefone;
    private javax.swing.JComboBox viewCadastroUF;
    private javax.swing.JTextField viewCadatroCidade;
    // End of variables declaration//GEN-END:variables

    private void salvarCliente() {
        try {
            modelCliente.setCliNome(this.viewCadastroCodigo.getText());

        } catch (NumberFormatException e) {
        }
        modelCliente.setCliNome(this.viewCadastroNome.getText().toUpperCase());
        modelCliente.setCliEndereco((this.viewCadastroEndereco.getText()).toUpperCase());
        modelCliente.setCliBairro(this.viewCadastroBairro.getText().toUpperCase());
        modelCliente.setCliCidade(this.viewCadatroCidade.getText().toUpperCase());
        modelCliente.setCliUF(this.viewCadastroUF.getSelectedItem().toString());
        modelCliente.setClicep(this.viewCadastroCEP.getText());
        modelCliente.setCliTelefone(this.viewCadastroTelefone.getText());

        if (controllerModelCliente.salvarclienteController(modelCliente) > 0) {
            JOptionPane.showMessageDialog(this, "Cliente salvo com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            this.carregarCliente();
            this.limparTela();
            this.habilitarDesabilitar(false);

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o cliente!", "Erro", JOptionPane.ERROR_MESSAGE);

        }

    }

    private void alterarCliente() {
        modelCliente.setCliNome(this.viewCadastroNome.getText().toUpperCase());
        modelCliente.setCliEndereco((this.viewCadastroEndereco.getText().toUpperCase()));
        modelCliente.setCliBairro(this.viewCadastroBairro.getText().toUpperCase());
        modelCliente.setCliCidade(this.viewCadatroCidade.getText().toUpperCase());
        modelCliente.setCliUF(this.viewCadastroUF.getSelectedItem().toString());
        modelCliente.setClicep(this.viewCadastroCEP.getText());
        modelCliente.setCliTelefone(this.viewCadastroTelefone.getText());

        if (controllerModelCliente.atualizarclienteController(modelCliente)) {
            JOptionPane.showMessageDialog(this, "Cliente Alterado com sucesso!", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            this.carregarCliente();
            this.limparTela();
            this.habilitarDesabilitar(false);

        } else {
            JOptionPane.showMessageDialog(this, "Erro ao alterar o cliente!", "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }

    void carregarCliente() {
        listaModelCliente = controllerModelCliente.getListaclienteController();

        DefaultTableModel modelo = (DefaultTableModel) viewCadastroTabela.getModel();
        
        modelo.setRowCount(0);
        // inserir prodtus na tabela
        for (int i = 0; i < listaModelCliente.size(); i++) {
            modelo.addRow(new Object[]{
                listaModelCliente.get(i).getIdCliente(),
                listaModelCliente.get(i).getCliNome(),
                listaModelCliente.get(i).getCliCidade(),
                listaModelCliente.get(i).getCliTelefone()
            });
        }
    }

    void limparTela() {
        viewCadastroNome.setText("");
        viewCadastroEndereco.setText("");
        viewCadastroBairro.setText("");
        viewCadatroCidade.setText("");
        viewCadastroCEP.setText("");
        viewCadastroTelefone.setText("");
    }

    private void habilitarDesabilitar(boolean codicao) {
        viewCadastroNome.setEnabled(codicao);
        viewCadastroEndereco.setEnabled(codicao);
        viewCadastroBairro.setEnabled(codicao);
        viewCadatroCidade.setEnabled(codicao);
        viewCadastroCEP.setEnabled(codicao);
        viewCadastroTelefone.setEnabled(codicao);
    }
}
